#!/bin/bash

# Print Usage
function usage () {
    echo "Usage: dtach [name] [cmd]"
    echo "    -h : print this help message"
}

# Script Scope Variables
SESSIONDIR="/tmp/dtach/"

# Function Definitions
function makeDir () {
    mkdir -p /tmp/dtach/
}

function listDir () {
    ls -1 ${SESSIONDIR}
}

function dt () {
    dtach ${mode} ${SESSIONDIR}${name} ${command}
}

function create () {
    mode="-c"
    dt
}

function attach () {
    mode="-a"
    dt
    if [[ $? -ne 0 ]]; then
        command="bash"
        create
    fi
}


# CMD Line Parsing and the body of the script

makeDir

if [[ $# -eq 0 ]]; then
    listDir
elif [[ $# -eq 1 ]]; then
    if [[ $1 = "-h" ]]; then
        usage
        exit
    elif [[ $1 = "--help" ]]; then
        usage
        exit
    elif [[ $1 = "-n" ]]; then
        usage
        exit
    fi
    name="${1}"
    command=""
    attach
elif [[ $# -eq 2 ]]; then
    if [[ $1 = "-n" ]]; then
        name="${2}"
        command="bash"
        mode="-n"
        dt
    fi
    name="${1}"
    command="${2}"
    create
elif [[ $# -eq 3 ]]; then
    if [[ $1 = "-n" ]]; then
        name="${2}"
        command="${3}"
        mode="-n"
        dt
    else
        usage
        exit
    fi
else
    usage
    exit
fi
