#!/bin/bash

# Copyright 2015 Curtis Sand
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Print Usage
function usage () {
    echo "Usage: dtach [name] [cmd]"
    echo "    -h : print this help message"
}

# Script Scope Variables
SESSIONDIR="/tmp/dtach/"

# Function Definitions
function makeDir () {
    mkdir -p /tmp/dtach/
}

function listDir () {
    ls -1 ${SESSIONDIR}
}

function dt () {
    dtach ${mode} ${SESSIONDIR}${name} ${command}
}

function create () {
    mode="-c"
    dt
}

function attach () {
    mode="-a"
    dt
    if [[ $? -ne 0 ]]; then
        command="bash"
        create
    fi
}


# CMD Line Parsing and the body of the script

makeDir

if [[ $# -eq 0 ]]; then
    listDir
elif [[ $# -eq 1 ]]; then
    if [[ $1 = "-h" ]]; then
        usage
        exit
    elif [[ $1 = "--help" ]]; then
        usage
        exit
    elif [[ $1 = "-n" ]]; then
        usage
        exit
    fi
    name="${1}"
    command=""
    attach
elif [[ $# -eq 2 ]]; then
    if [[ $1 = "-n" ]]; then
        name="${2}"
        command="bash"
        mode="-n"
        dt
    fi
    name="${1}"
    command="${2}"
    create
elif [[ $# -eq 3 ]]; then
    if [[ $1 = "-n" ]]; then
        name="${2}"
        command="${3}"
        mode="-n"
        dt
    else
        usage
        exit
    fi
else
    usage
    exit
fi
