#!/bin/bash

# Copyright 2016 Curtis Sand
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# TODO: add a "-c|--clean" option that will check for and remove obsolete
#       switch files.

CMD=$@
echo $CMD
exit

# Use a tmp file as an on/off switch
SWITCH="/tmp/dowhile.$$"

# Create the switch file
touch $SWITCH

count=0

# While the tmp file exists repeat the command forever
while [ -f $SWITCH ]; do
    $CMD
    count=$((count + 1))
    echo "starting cycle $count..."
    sleep 1;
done
