#!/bin/bash

# Copyright 2015 Curtis Sand
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Construct an HTML Redirect page to the Public IP Address

GET_IP="$(dirname $0)/get_public_ip"

echo -en "<DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0 Transitional//EN\">\n"
echo -en "<html>\n<head>\n<title>Fret's Home</title>\n"
#echo -en "<meta http-equiv=\"REFRESH\" content=\"0;url=http://$(${GET_IP})\">\n"
echo -en "</head>\n<body>$(${GET_IP})</body>\n</html>\n"
