#!/bin/bash

# Copyright 2015 Curtis Sand
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

usage () {
    echo -en "$0 [INTERFACE]"
    echo -en "\nRetrieve the Local IP address assigned to the given interface. "
    echo -e "Default interface is eth0"
    exit 0;
}

INTERFACE=eth0
if [[ $# -eq 1 ]]; then
    if [[ "${1:0:2}" == "-h" ]] || [[ "${1:0:3}" == "--h" ]]; then
        usage;
    fi
    INTERFACE=$1;
elif [[ $# -gt 1 ]]; then
    usage;
fi

ip addr show dev $INTERFACE | grep inet | grep -v inet6 |\
    sed -e 's/^ \+inet //g' -e 's/\/[0-9]\+ brd.*$//g'
