#!/bin/bash

# Copyright 2015 Curtis Sand
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

SCRIPT=$0
ADDRESSES=""
DESTINATION="/tmp/"
USER=

usage () {
    local opts="[-h|--help|-a|--address|-d|--destination|-u|--user]"
    echo "$SCRIPT $opts FILE1 FILE2 ...";
    echo -e "\nmscp is scp for sending files to multiple machines.\nOptions"
    echo "  -h|--help         Show this help message."
    echo "  -a|--address      Add an address to send the files to. "
    echo "                    Can be used multiple times."
    echo "  -d|--destination  Set the destination for the files."
    echo "                    [Default: '$DESTINATION']"
    echo "  -u|--user         User to use on remote hosts. "
    echo "                    Defaults to current user."
    local rc=0
    [ -n "$1" ] && rc=$1
    exit $rc
}

die () {
    echo $@
    exit 1
}

ARGS=$(getopt -o "ha:d:u:" -l "help,address:,destination:user:" \
              -n $SCRIPT -- "$@")
[ $? -ne 0 ] && usage 1  # bad arguments found

eval set -- "$ARGS"
while true ; do
    case "$1" in
        -h|--help) usage ; shift ;;
        -a|--address) ADDRESSES="$ADDRESSES $2" ; shift 2 ;;
        -d|--destination) DESTINATION="$2" ; shift 2 ;;
        -u|--user) USER="$2" ; shift 2 ;;
        --) shift ; break ;;
        *) echo "Internal error!" ; exit 1 ;;
    esac
done

FILES=$@

[ -z "$ADDRESSES" ] && \
    die "$SCRIPT requires host addresses to send the files to."
[ -z "$FILES" ] && die "$SCRIPT requires FILES to send."
[ -z "$DESTINATION" ] && die "$SCRIPT requires files to send."

for ip in $ADDRESSES; do
    echo "ip: $ip"
    dest=
    [ -n $USER ] && dest="${USER}@"
    dest="$dest$ip:$DESTINATION"
    scp -r $FILES $dest
done
