#!/usr/bin/env python

# Copyright 2015 Curtis Sand
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

""" nisDiscover.py discovers all of the details of the nis maps available
    through the system's default map and writes a report.
"""
import os, sys, optparse, nis, time

def parseCmdLine():
    """
    manage cli invocation
    """
    usage = '%prog REPORTFILE'
    version = '%prog v0.0'
    description = __doc__
    parser = optparse.OptionParser( usage = usage,
                           version = version,
                           description = description )
    opts, args = parser.parse_args()
    if len(args) != 1:
        parser.error('%prog expects 1 positional argument, REPORTFILE.')

    return (opts, args)

def getTitle():
    ts = time.strftime("%Y/%m/%d %H:%M:%S", time.gmtime())
    return "%s\n%s\n" % (ts, '-' * len(ts))

def main():
    opts, args = parseCmdLine()
    logFile = args[0]
    if os.path.exists(logFile):
        raise Exception('Please choose a REPORTFILE that does not yet exist.')

    maps = nis.maps()
    with open(logFile, 'w') as log:
        log.write(getTitle())
        log.write('\nNIS Maps of domain: %s\n' % nis.get_default_domain())
        log.write('List of NIS Maps present:\n\n%s\n\n' %
                  '\n'.join(['- %s' % mapname for mapname in maps]))
        for mapname in maps:
            log.write('\n%s:\n' % mapname)
            entries = nis.cat(mapname)
            for key, value in entries.iteritems():
                log.write('  "%s" : "%s"\n' % (key, value))
            log.write('\n' + '-' * 80 + '\n')

    return 0

if __name__ == '__main__':
    sys.exit(main())
