#!/bin/bash

# Copyright 2015 Curtis Sand
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# $(($(date +%s) - $(stat --format "%X"  /proc/15473/cmdline)))

SCRIPT=$0

usage () {
    echo "$SCRIPT [-h|--help] PID";
    echo "Calculate the number of seconds a process has been running for."
    exit 1;
}

ARGS=`getopt -o "h" -l "help" -n "template.sh" -- "$@"`
if [ $? -ne 0 ]; then
    # bad arguments found
    exit 1;
fi
eval set -- "$ARGS"

while true ; do
        case "$1" in
                -h|--help) usage ; shift ;;
                --) shift ; break ;;
                *) echo "Internal error!" ; exit 1 ;;
        esac
done

if [[ $# -ne 1 ]]; then
    echo "$SCRIPT only expects a single parameter.";
    usage;
fi

pid=$1
if [[ ! -d /proc/$pid ]] || [[ ! -f /proc/$pid/cmdline ]]; then
    echo "Could not find '/proc/$pid' or '/proc/$pid/cmdline'."
    exit 1;
fi

echo $(($(date +%s) - $(stat --format "%X"  /proc/$pid/cmdline)))
