#!/usr/bin/env python
'''
Generate random numbers within given ranges.  If run with a single argument,
will generate an integer between 0 and the argument otherwise it will generate
an integer between arg1 and arg2.  A '-f' option should be added later to
generate floating point numbers.
'''
import sys, optparse, random


def parseCmdLine():
    '''
    manage cli invocation
    '''
    usage = '%prog [max]  or  %prog [min] [max]'
    version = '%prog v0.0'
    description = __doc__
    parser = optparse.OptionParser( usage = usage, 
                           version = version,
                           description = description )
    return parser.parse_args()

def main():
    opts, args = parseCmdLine()
    if len(args) == 1:
        max = int(args[0])
        min = 0
    elif len(args) == 2:
        max = int(args[1])
        min = int(args[0])
    else:
        print "Wrong number of arguments\n"
        print 'random [max]  or  random [min] [max]'
        return 1

    print random.randint(min,max)
    return 0


if __name__ == '__main__':
    try:
        sys.exit( main() )
    except KeyboardInterrupt:
        print 'Interrupted by User.'
        sys.exit( 1 )


