#!/bin/bash

# Copyright 2015 Curtis Sand
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if [ $# -eq 0 ]
    then
    find . -name "*.pyc" | xargs rm -f
    find . -name "*.pyo" | xargs rm -f
    find . -name "__pycache__" | xargs rm -rf
elif [ $# -eq 1 ]
    then
    find $1 -name "*.pyc" | xargs rm -f
    find $1 -name "*.pyo" | xargs rm -f
    find $1 -name "__pycache__" | xargs rm -rf
else
    echo "Usage: rmpyc [dir-to-search-in]"
    exit 1
fi
