#!/bin/bash

if [ $# -eq 0 ]
    then
    find . -name "*.pyc" | xargs rm -f
    find . -name "*.pyo" | xargs rm -f
elif [ $# -eq 1 ]
    then
    find $1 -name "*.pyc" | xargs rm -f
    find $1 -name "*.pyo" | xargs rm -f
else
    echo "Usage: rmpyc [dir-to-search-in]"
    exit 1
fi

