#!/bin/bash

# Copyright 2015 Curtis Sand
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

usage () {
    echo "$0 [PORT]"
    echo -en "\nServe the current working directory on given port. "
    echo -e "Port defaults to 8000."
    exit 0;
}

PORT=8000
for arg in $@; do
    if [[ "${arg:0:2}" == "-h" ]] || [[ "${arg:0:3}" == "--h" ]]; then
        usage;
    fi
done

if [[ $# -eq 1 ]]; then
    PORT=$1
    DIR=
elif [[ $# -eq 2 ]]; then
    PORT=$1
    DIR=$2
elif [[ $# -gt 2 ]]; then
    usage;
fi

if [[ ! -z $DIR ]]; then
    cd $DIR
fi
#python -m SimpleHTTPServer $PORT

python -c "import SimpleHTTPServer, SocketServer, BaseHTTPServer; SimpleHTTPServer.test(SimpleHTTPServer.SimpleHTTPRequestHandler, type('Server', (BaseHTTPServer.HTTPServer, SocketServer.ThreadingMixIn, object), {}))" $PORT
