#!/bin/bash

args=("$@")
unset args[0]

sleep ${1}

cvlc --play-and-exit --loop ${HOME}/stuff/misc/plane_2.mp3 >> /dev/null 2>&1 &

VLCPID=`echo $!`

zenity --info --text "`echo ${args[@]}`" && kill ${VLCPID} &
