#!/bin/bash

# Copyright 2015 Curtis Sand
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

SCRIPT=$0

usage () {
    echo "$SCRIPT [-h|--help] PATH";
    exit 1;
}

# Options with no args have no colon
# Option with required arg has 1 colon
# Option with optional arg has 2 colons
ARGS=`getopt -o "h" -l "help" -n "${0}" -- "$@"`
if [ $? -ne 0 ]; then
    # bad arguments found
    exit 1;
fi
eval set -- "$ARGS"

while true ; do
        case "$1" in
                -h|--help) usage ; shift ;;
                #-b|--b-long) echo "Option b, argument \`$2'" ; shift 2 ;;
                #-c|--c-long)
                #        # c has an optional argument. As we are in quoted mode,
                #        # an empty parameter will be generated if its optional
                #        # argument is not found.
                #        case "$2" in
                #                "") echo "Option c, no argument"; shift 2 ;;
                #                *)  echo "Option c, argument \`$2'" ; shift 2 ;;
                #        esac ;;
                --) shift ; break ;;
                *) echo "Internal error!" ; exit 1 ;;
        esac
done

path="${1%/}"
tmp_path="${path}.tmp"

if [[ -f ${path} ]] || [[ -d ${path} ]]; then
    cp -r ${path} ${tmp_path} && rm -r ${path} && mv ${tmp_path} ${path}
else
    echo "Path ${path} doesn't appear to exist"
fi
