#!/bin/bash

#Edit this variable to match the location of your maildir
log=/home/csand/storage/gmail/.offlineimap.log

function usage() {
    echo "mail.sh : mail related tasks for curtis's laptop"
    echo "    Usage: > mailsync.sh [options]"
    echo "    Options:"
    echo "        '-h' : display this help message"
    echo "        '-w' : watch offlineimap's log"
    echo "        '-s' : start offlineimap"
    echo "        '-k' : kill offlineimap"
    echo "        '-p' : return pid of offlineimap if it has one"
}

offlineimap=/usr/bin/offlineimap

function getpid() {
    pid=`pidof -x ${offlineimap}`
}
getpid

function watch() {
    /usr/bin/watch -n 1 "tail -n 40 ${log}"
}

function startDaemon() {
    ${offlineimap} 2>&1 > ${log} &
    sleep 2
    getpid
    echo ${pid}
}

if [[ $# -eq 0 ]]; then
    # start offlineimap if it's not started already
    if [[ -z $pid ]]; then
        startDaemon
    else
        watch
    fi
elif [[ $# -eq 1 ]]; then
    # do option
    if [[ $1 = '-h' ]]; then
        usage
    elif [[ $1 = '-w' ]]; then
        watch
    elif [[ $1 = '-s' ]]; then
        if [[ -z $pid ]]; then
            startDaemon
        else
            echo "Already started on pid=${pid}"
        fi
    elif [[ $1 = '-k' ]]; then
        if [[ -n ${pid} ]]; then
            kill ${pid}
        fi
    elif [[ $1 = '-p' ]]; then
        echo ${pid}
    else
        usage
    fi
else
    usage
fi
