#!/bin/bash

# Copyright 2015 Curtis Sand
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ytdl-queue
#
# This script queues a youtube download by calling zenity to get a URL and
# filename from the user. The queued job is stored in the $QUEUE directory with
# the URL as the content.

QUEUE="/home/csand/storage/tmp/youtube/queue"

url="$(zenity --entry --text "URL to download:" 2>/dev/null)"
fname="$(zenity --entry --text "Output filename (no suffix, no sub-dirs):" \
    2>/dev/null)"

echo $url > ${QUEUE}/${fname}
