#!/usr/bin/env python
'''
Project Euler Problem 2

Completed 20091105
'''
import sys

class Filo:
    '''
    Implementation of a Filo Queue
    
    push in order the # 1, 2, 3 and get: [1, 2, 3]
    pop and get [1, 2]
    '''
    def __init__( self, *args ):
        self._data = list(args)

    def push( self, *args ):
        for arg in list(args):
            self._data.append(arg)
        return self._data

    def pop( self ):
        return self._data.pop(0)

    def __str__( self ):
        return str(self._data)
    

class Fibonacci:
    '''
    An implementation of a fibonacci sequence.
    '''
    def __init__( self, a, b ):
        self.a = a
        self.b = b
        self.filo = Filo()
        self.filo.push( self.a, self.b )

    def next( self ):
        '''
        calculate the next term in the fibonacci sequence
        '''
        self.a = self.b
        self.b = self.a + self.filo.pop()
        self.filo.push( self.b )
        return self.b


def main():
    '''
    Each new term in the Fibonacci sequence is generated by adding the
    previous two terms. By starting with 1 and 2, the first 10 terms
    will be:
    
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    
    Find the sum of all the even-valued terms in the sequence which do
    not exceed four million.

    Solution: Adding two odd numbers or two even numbers together
    result in an even number.  In the fibonacci sequence every even
    number is separated by 2 odd numbers.
    1  2  3  5  8  13 21 34 55 89
    0  1  2  3  4  5  6  7  8  9
    '''
    theSum = 2
    target = 4
    fib = Fibonacci(1, 2)
    num = fib.next()
    currentTerm = 2
    while num <= 4000000:
        print num
        if currentTerm is target:
            theSum += num
            target += 3
        num = fib.next()
        currentTerm += 1
    
    print ( 'The sum of all the even-valued terms in the fibonacci '
            'sequence which do not exceed four million is: %s' % theSum )
    return 0

if __name__ == '__main__':
    try:
        sys.exit( main() )
    except KeyboardInterrupt:
        print 'Interrupted by User.'
        sys.exit( 1 )


